-- Synra production schema for Neon (Postgres). GENERATED by scripts/neon-schema.ts — do not edit.
--
-- Applies every migration in drizzle/ (0000_high_lionheart, 0001_alpaca_orders, 0002_screening_criteria, 0003_market_orders) that the database's
-- drizzle journal does not list yet, and records it there exactly as `bun run db:migrate` would. Works on an empty
-- database and on one already partly migrated; safe to run more than once.
--
-- Usage: paste into the Neon SQL editor, or
--   psql "$PRODUCTION_DATABASE_URL" -f scripts/neon-schema.sql
-- (equivalent: NODE_ENV=production bun run db:migrate)
--
-- When lib/db/schema.ts changes: `bun run db:generate`, then `bun run db:neon-schema` to refresh this file.

BEGIN;

CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
	"id" serial PRIMARY KEY,
	"hash" text NOT NULL,
	"created_at" bigint
);

-- 0000_high_lionheart
DO $migration$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE "hash" = 'ec5d2f4e3c0f5b12728fe1e7c26b7d36a3857f81bbcf05542ce57ca90e66b71f') THEN
		EXECUTE $stmt$CREATE TABLE "filings" (
	"accession" text PRIMARY KEY NOT NULL,
	"cik" text NOT NULL,
	"issuer_cik" text,
	"issuer_name" text,
	"ticker" text,
	"insider_cik" text,
	"insider_name" text,
	"insider_role" text,
	"feed_updated" timestamp with time zone NOT NULL,
	"filed_date" text,
	"period_of_report" text,
	"status" text NOT NULL,
	"reason" text,
	"run_id" integer,
	"attempts" integer DEFAULT 0 NOT NULL,
	"processed_at" timestamp with time zone,
	"index_url" text,
	"xml_url" text,
	"form" jsonb
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "form4_cache" (
	"accession" text PRIMARY KEY NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"form" jsonb NOT NULL
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "insider_analyses" (
	"id" serial PRIMARY KEY NOT NULL,
	"accession" text NOT NULL,
	"insider_cik" text NOT NULL,
	"issuer_cik" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"model" text NOT NULL,
	"classification" text NOT NULL,
	"confidence" double precision,
	"reasoning" text,
	"pattern_summary" text,
	"history" jsonb,
	"prompt_tokens" integer,
	"completion_tokens" integer
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "insiders" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"title" text,
	"relationship" text,
	"company" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "issuer_cache" (
	"cik" text PRIMARY KEY NOT NULL,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL,
	"profile" jsonb NOT NULL
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "kv" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "poll_runs" (
	"id" serial PRIMARY KEY NOT NULL,
	"trigger" text NOT NULL,
	"status" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"cursor_before" text,
	"cursor_after" text,
	"feed_entries" integer DEFAULT 0 NOT NULL,
	"new_filings" integer DEFAULT 0 NOT NULL,
	"skipped_10b5_1" integer DEFAULT 0 NOT NULL,
	"skipped_sell" integer DEFAULT 0 NOT NULL,
	"skipped_not_purchase" integer DEFAULT 0 NOT NULL,
	"skipped_routine" integer DEFAULT 0 NOT NULL,
	"posted" integer DEFAULT 0 NOT NULL,
	"errors" integer DEFAULT 0 NOT NULL,
	"error" text
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "stocks" (
	"id" text PRIMARY KEY NOT NULL,
	"ticker" text,
	"company_name" text NOT NULL,
	"exchange" text,
	"sector" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);$stmt$;
		EXECUTE $stmt$CREATE TABLE "trades" (
	"id" text PRIMARY KEY NOT NULL,
	"insider_id" text NOT NULL,
	"stock_id" text NOT NULL,
	"trade_type" text NOT NULL,
	"shares" bigint NOT NULL,
	"price_per_share" numeric(18, 4),
	"total_value" numeric(18, 2),
	"trade_date" text,
	"filing_date" text,
	"posted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"shares_after" double precision,
	"transactions" jsonb NOT NULL,
	"ai_classification" text,
	"ai_confidence" double precision,
	"ai_reasoning" text,
	"ai_pattern" text,
	"ai_model" text,
	"history" jsonb,
	"filing_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);$stmt$;
		EXECUTE $stmt$ALTER TABLE "filings" ADD CONSTRAINT "filings_run_id_poll_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."poll_runs"("id") ON DELETE no action ON UPDATE no action;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD CONSTRAINT "trades_insider_id_insiders_id_fk" FOREIGN KEY ("insider_id") REFERENCES "public"."insiders"("id") ON DELETE no action ON UPDATE no action;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD CONSTRAINT "trades_stock_id_stocks_id_fk" FOREIGN KEY ("stock_id") REFERENCES "public"."stocks"("id") ON DELETE no action ON UPDATE no action;$stmt$;
		EXECUTE $stmt$CREATE INDEX "filings_status_idx" ON "filings" USING btree ("status");$stmt$;
		EXECUTE $stmt$CREATE INDEX "filings_feed_updated_idx" ON "filings" USING btree ("feed_updated" DESC NULLS LAST);$stmt$;
		EXECUTE $stmt$CREATE INDEX "insider_analyses_accession_idx" ON "insider_analyses" USING btree ("accession");$stmt$;
		EXECUTE $stmt$CREATE INDEX "stocks_ticker_idx" ON "stocks" USING btree ("ticker");$stmt$;
		EXECUTE $stmt$CREATE INDEX "trades_stock_id_idx" ON "trades" USING btree ("stock_id");$stmt$;
		EXECUTE $stmt$CREATE INDEX "trades_insider_id_idx" ON "trades" USING btree ("insider_id");$stmt$;
		EXECUTE $stmt$CREATE INDEX "trades_trade_date_idx" ON "trades" USING btree ("trade_date" DESC NULLS LAST);$stmt$;
		EXECUTE $stmt$CREATE INDEX "trades_posted_at_idx" ON "trades" USING btree ("posted_at" DESC NULLS LAST);$stmt$;
		INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('ec5d2f4e3c0f5b12728fe1e7c26b7d36a3857f81bbcf05542ce57ca90e66b71f', 1789931978694);
	END IF;
END $migration$;

-- 0001_alpaca_orders
DO $migration$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE "hash" = '9e4aa34069fa1c1ff881f3836d5419379c08c3e24c68e5094b6afa26a1558dc3') THEN
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_id" text;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_client_order_id" text;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_status" text;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_notional" numeric(18, 2);$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_qty" double precision;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_error" text;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_ordered_at" timestamp with time zone;$stmt$;
		INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('9e4aa34069fa1c1ff881f3836d5419379c08c3e24c68e5094b6afa26a1558dc3', 1789940042568);
	END IF;
END $migration$;

-- 0002_screening_criteria
DO $migration$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE "hash" = '52eba346afea449349020d536f6177c443ca3464be6f2da821a16bc98b50fe41') THEN
		EXECUTE $stmt$ALTER TABLE "insider_analyses" RENAME COLUMN "model" TO "classifier";$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" RENAME COLUMN "ai_classification" TO "classification";$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" RENAME COLUMN "ai_reasoning" TO "reasoning";$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" RENAME COLUMN "ai_pattern" TO "pattern_summary";$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" RENAME COLUMN "ai_model" TO "classifier";$stmt$;
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "skipped_listing" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "skipped_history" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "skipped_market_cap" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "skipped_price" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "market_cap" double precision;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "quote_price" numeric(18, 4);$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_order_limit_price" numeric(18, 4);$stmt$;
		EXECUTE $stmt$ALTER TABLE "insider_analyses" DROP COLUMN "confidence";$stmt$;
		EXECUTE $stmt$ALTER TABLE "insider_analyses" DROP COLUMN "prompt_tokens";$stmt$;
		EXECUTE $stmt$ALTER TABLE "insider_analyses" DROP COLUMN "completion_tokens";$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" DROP COLUMN "ai_confidence";$stmt$;
		INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('52eba346afea449349020d536f6177c443ca3464be6f2da821a16bc98b50fe41', 1790828772525);
	END IF;
END $migration$;

-- 0003_market_orders
DO $migration$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE "hash" = '0c3bd9c087e6173adead8a6ad0b56fa092260a5437d9a309fb55f2bdd11df8a3') THEN
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "skipped_order" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "poll_runs" ADD COLUMN "deferred" integer DEFAULT 0 NOT NULL;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_filled_qty" double precision;$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_filled_avg_price" numeric(18, 4);$stmt$;
		EXECUTE $stmt$ALTER TABLE "trades" ADD COLUMN "alpaca_filled_at" timestamp with time zone;$stmt$;
		INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('0c3bd9c087e6173adead8a6ad0b56fa092260a5437d9a309fb55f2bdd11df8a3', 1790869002706);
	END IF;
END $migration$;

COMMIT;
