/**
 * Regenerates scripts/planet-schema.sql from drizzle/*.sql: `bun run db:planet-schema`.
 *
 * Each migration is wrapped in a block that, like drizzle's migrator, runs only if the journal has no migration at or
 * after its created_at (`when` in drizzle/meta/_journal.json), then records it with the same hash (sha256 of the file)
 * and created_at that `bun run db:migrate` would write. So the SQL file and db:migrate can be mixed freely on the same
 * database. (The squashed 0000_init keeps the old 0005's `when`, so databases migrated before the squash skip it.)
 */
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync } from "node:fs"

const journal = JSON.parse(
  readFileSync("drizzle/meta/_journal.json", "utf8")
) as {
  entries: { idx: number; when: number; tag: string }[]
}

const blocks = journal.entries.map(({ tag, when }) => {
  const sql = readFileSync(`drizzle/${tag}.sql`, "utf8")
  const hash = createHash("sha256").update(sql).digest("hex")
  const statements = sql
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter(Boolean)
  for (const s of statements)
    if (s.includes("$stmt$")) throw new Error(`${tag} contains "$stmt$"`)
  return `-- ${tag}
DO $migration$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM "drizzle"."__drizzle_migrations" WHERE "created_at" >= ${when}) THEN
${statements.map((s) => `\t\tEXECUTE $stmt$${s}$stmt$;`).join("\n")}
		INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('${hash}', ${when});
	END IF;
END $migration$;`
})

const out = `-- Synra production schema for PlanetScale (Postgres). GENERATED by scripts/planet-schema.ts — do not edit.
--
-- Applies every migration in drizzle/ (${journal.entries.map((e) => e.tag).join(", ")}) that the database's
-- drizzle journal does not list yet, and records it there exactly as \`bun run db:migrate\` would. Works on an empty
-- database and on one already partly migrated; safe to run more than once.
--
-- Usage (as the DDL role in DIRECT_URL):
--   psql "$DIRECT_URL" -f scripts/planet-schema.sql
-- (equivalent: NODE_ENV=production bun run db:migrate)
--
-- When lib/db/schema.ts changes: \`bun run db:generate\`, then \`bun run db:planet-schema\` to refresh this file.

BEGIN;

CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
	"id" serial PRIMARY KEY,
	"hash" text NOT NULL,
	"created_at" bigint
);

${blocks.join("\n\n")}

COMMIT;
`
writeFileSync("scripts/planet-schema.sql", out)
console.log(
  `[synra] wrote scripts/planet-schema.sql (${journal.entries.length} migrations)`
)
